const storageKey='service_l90_data_v2';let data={car:{name:'L90',plate:'',km:12000},services:[]};
function load(){try{const raw=localStorage.getItem(storageKey);if(raw)data=JSON.parse(raw);}catch(e){console.error(e);}renderCar();renderServices();renderDashboard();}
function save(){localStorage.setItem(storageKey,JSON.stringify(data));}
function renderCar(){document.getElementById('carName').value=data.car.name||'';document.getElementById('carPlate').value=data.car.plate||'';document.getElementById('carKm').value=data.car.km||0;}
function renderServices(){const el=document.getElementById('serviceList');el.innerHTML='';data.services.forEach((s,idx)=>{const div=document.createElement('div');div.className='svc';div.innerHTML=`<div><strong>${s.title}</strong><div class="small">${s.date||''} ${s.km?' - '+s.km+' km':''}</div><div class="small">${s.notes||''}</div></div><div><button onclick="markDone(${idx})">${s.done?'✔️':'⭕'}</button><button onclick="removeSvc(${idx})">🗑️</button></div>`;el.appendChild(div);});}
function renderDashboard(){const el=document.getElementById('dashboard');el.innerHTML='';const upcoming=data.services.filter(s=>!s.done&&((s.date&&daysUntil(s.date)<=7&&daysUntil(s.date)>=0)||(s.km&&(s.km-(data.car.km||0))<=500&&(s.km-(data.car.km||0))>=0)));if(upcoming.length===0){el.innerHTML='<p class="small">سرویسی نزدیک نیست.</p>';return;}upcoming.forEach(s=>{const d=document.createElement('div');d.className='svc';d.innerHTML=`<div><strong>${s.title}</strong><div class="small">${s.date||''} ${s.km?' - '+s.km+' km':''}</div></div>`;el.appendChild(d);});}
function daysUntil(dateStr){if(!dateStr)return 9999;const d=new Date(dateStr);return Math.ceil((d-new Date())/(1000*60*60*24));}
document.getElementById('saveCar').addEventListener('click',()=>{data.car.name=document.getElementById('carName').value||'L90';data.car.plate=document.getElementById('carPlate').value||'';data.car.km=parseInt(document.getElementById('carKm').value||0);save();renderCar();alert('اطلاعات خودرو ذخیره شد');renderDashboard();});
document.getElementById('addSvc').addEventListener('click',()=>{const s={title:document.getElementById('svcTitle').value||'',date:document.getElementById('svcDate').value||'',km:document.getElementById('svcKm').value?parseInt(document.getElementById('svcKm').value):null,notes:document.getElementById('svcNotes').value||'',done:false};if(!s.title){alert('عنوان سرویس را وارد کنید');return;}data.services.push(s);save();renderServices();renderDashboard();document.getElementById('svcTitle').value='';document.getElementById('svcDate').value='';document.getElementById('svcKm').value='';document.getElementById('svcNotes').value='';});
function markDone(i){data.services[i].done=!data.services[i].done;save();renderServices();renderDashboard();}
function removeSvc(i){if(confirm('آیا حذف شود؟')){data.services.splice(i,1);save();renderServices();renderDashboard();}}
document.getElementById('clearData').addEventListener('click',()=>{if(confirm('همه داده‌ها حذف شود؟')){data={car:{name:'L90',plate:'',km:12000},services:[]};save();load();}});
document.getElementById('themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light');});
window.addEventListener('load',()=>{const t=localStorage.getItem('theme')||'light';if(t==='dark')document.body.classList.add('dark');load();});
